// Bridge/tunnel sidecar generator (Phase A.1, road-compiler roadmap §3 / Checkpoint ②).
//
// One-time, OFFLINE Overpass query for drivable `bridge`/`tunnel` ways over a region bbox, emitted as a
// compact static TS map { osmWayId: { bridge?, tunnel?, layer, lanes? } }. This is the tag data that the
// streets.gl PBF vector tiles STRIP (`bridge`/`layer`/`tunnel` are absent from the PBF schema); the
// decode-time join (VectorTileLineStringHandler) stamps it back onto features by osmId.
//
// NOT in any hot path — run by hand to (re)generate the asset, then commit the output.
//
//   node scripts/genBridgeSidecar.mjs sf
//   node scripts/genBridgeSidecar.mjs sf --out /tmp/sfBridgeSidecar.generated.ts
//
// Re-run to follow OSM drift. Data © OpenStreetMap contributors (ODbL) — see roadmap §5.

import fs from 'node:fs';
import path from 'node:path';
import {fileURLToPath} from 'node:url';

const OVERPASS = 'https://overpass-api.de/api/interpreter';

// Region bboxes: [south, west, north, east]. SF "wide" bbox contains both full bridge spans
// (GGB north end + Bay Bridge toward Oakland), confirmed at Checkpoint ①.
const REGIONS = {
	sf: {bbox: [37.70, -122.53, 37.84, -122.28], label: 'San Francisco'}
};

// The drivable network only — footway/cycleway/path/steps bridges are real OSM bridges but irrelevant to
// the driving sim, and keep the asset small + the magenta highlight signal clean.
const DRIVABLE = new Set([
	'motorway', 'trunk', 'primary', 'secondary', 'tertiary', 'unclassified', 'residential',
	'living_street', 'motorway_link', 'trunk_link', 'primary_link', 'secondary_link',
	'tertiary_link', 'service'
]);

function parseLayer(raw, fallback) {
	if (raw === undefined || raw === null || raw === '') return fallback;
	const m = String(raw).match(/-?\d+/); // handles "1", "-1", "1;2"
	return m ? parseInt(m[0], 10) : fallback;
}

function parseLanes(raw) {
	if (raw === undefined) return undefined;
	const m = String(raw).match(/\d+/);
	return m ? parseInt(m[0], 10) : undefined;
}

async function overpass(query) {
	const res = await fetch(OVERPASS, {
		method: 'POST',
		headers: {'Content-Type': 'application/x-www-form-urlencoded', 'User-Agent': 'strata-sidecar/0.1 (research)'},
		body: 'data=' + encodeURIComponent(query)
	});
	if (!res.ok) throw new Error(`Overpass ${res.status}: ${await res.text()}`);
	return res.json();
}

async function main() {
	const region = process.argv[2];
	if (!region || !REGIONS[region]) {
		console.error(`Usage: node scripts/genBridgeSidecar.mjs <${Object.keys(REGIONS).join('|')}> [--out PATH]`);
		process.exit(1);
	}
	const outIdx = process.argv.indexOf('--out');
	const here = path.dirname(fileURLToPath(import.meta.url));
	const outPath = outIdx !== -1
		? process.argv[outIdx + 1]
		: path.join(here, '..', 'src', 'lib', 'tile-processing', 'vector', 'sidecar', `${region}BridgeSidecar.generated.ts`);

	const {bbox, label} = REGIONS[region];
	const [s, w, n, e] = bbox;
	const query = `[out:json][timeout:120];
(
  way[highway][bridge](${s},${w},${n},${e});
  way[highway][tunnel](${s},${w},${n},${e});
);
out tags;`;

	console.error(`Querying Overpass for ${label} bridges/tunnels...`);
	const data = await overpass(query);
	const ways = data.elements.filter(el => el.type === 'way');

	const entries = [];
	let skipped = 0;
	for (const way of ways) {
		const t = way.tags || {};
		if (!DRIVABLE.has(t.highway)) {
			skipped++;
			continue;
		}
		const isBridge = t.bridge && t.bridge !== 'no';
		const isTunnel = t.tunnel && t.tunnel !== 'no';
		if (!isBridge && !isTunnel) continue;
		const entry = {};
		if (isBridge) entry.bridge = true;
		if (isTunnel) entry.tunnel = true;
		entry.layer = parseLayer(t.layer, isBridge ? 1 : -1);
		const lanes = parseLanes(t.lanes);
		if (lanes !== undefined) entry.lanes = lanes;
		entries.push([way.id, entry]);
	}
	entries.sort((a, b) => a[0] - b[0]);

	const lines = entries.map(([id, e]) => {
		const parts = [];
		if (e.bridge) parts.push('bridge:true');
		if (e.tunnel) parts.push('tunnel:true');
		parts.push(`layer:${e.layer}`);
		if (e.lanes !== undefined) parts.push(`lanes:${e.lanes}`);
		return `\t${id}: {${parts.join(', ')}},`;
	});

	const header = `// AUTO-GENERATED by scripts/genBridgeSidecar.mjs — do not edit by hand.
// Region: ${label}  bbox [S ${s}, W ${w}, N ${n}, E ${e}]  (drivable bridge/tunnel ways only)
// Generated ${new Date().toISOString()} from OSM via Overpass.
// Data © OpenStreetMap contributors (ODbL). Regenerate: node scripts/genBridgeSidecar.mjs ${region}

import type {BridgeSidecar, BridgeSidecarEntry} from "~/lib/tile-processing/vector/sidecar/BridgeSidecar";

const data: Record<number, BridgeSidecarEntry> = {
${lines.join('\n')}
};

export const ${region.toUpperCase()}_BRIDGE_SIDECAR: BridgeSidecar = data;
`;

	fs.writeFileSync(outPath, header, 'utf8');
	console.error(`Wrote ${entries.length} entries (${skipped} non-drivable ways skipped) -> ${outPath}`);
}

main().catch(err => {
	console.error(err);
	process.exit(1);
});
